JUNIT=-cp \
      ".;target/test-classes;target/classes;junit-4.12.jar;hamcrest-core-1.3.jar" \
      org.junit.runner.JUnitCore

test:
	java ${JUNIT} cs131.pa1.test.AllSequentialTests

clean:
	bash clean.sh
